name: Azure Static Web Apps CI/CD

on:
  # Trigger on pushes to the main branch
  push:
    branches:
      - main
    paths:
      - .github/workflows/azure-static-web-apps-react-pipeline.yml
      - 'app/client/**'
  
  # Trigger on pull request events targeting the main branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - .github/workflows/main_mern-employer-app.yml
      - 'app/client/**'

jobs:
  build_and_deploy_job:
    # Run job on push events or on pull request events that are not closed
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout code from repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      # Set environment variable for VITE_API_URL
      - name: Set VITE_API_URL
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> $GITHUB_ENV

      # Build and deploy the app to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_OCEAN_07A99C100 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Token for GitHub integrations
          action: "upload"
          app_location: "/app/client" # Path to the app source code
          api_location: "" # Path to API source code (optional)
          output_location: "dist" # Directory for built app content (optional)
        # env:
          # VITE_API_URL: ${{ secrets.VITE_API_URL }}

  close_pull_request_job:
    # Run job when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      # Close the pull request in Azure Static Web Apps
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_OCEAN_07A99C100 }}
          action: "close"
